export default {
  GET_MESSAGES_SUCCESSFUL: 'GET_MESSAGES_SUCCESSFUL',
  GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
  GET_MESSAGES_FAILED: 'GET_MESSAGES_FAILED',

  GET_MESSAGE_SUCCESSFUL: 'GET_MESSAGE_SUCCESSFUL',
  GET_MESSAGE_REQUEST: 'GET_MESSAGE_REQUEST',
  GET_MESSAGE_FAILED: 'GET_MESSAGE_FAILED',

  DELETE_MESSAGE_SUCCESSFUL: 'DELETE_MESSAGE_SUCCESSFUL',
  DELETE_MESSAGE_REQUEST: 'DELETE_MESSAGE_REQUEST',
  DELETE_MESSAGE_FAILED: 'DELETE_MESSAGE_FAILED',

  STAR_MESSAGE_SUCCESSFUL: 'STAR_MESSAGE_SUCCESSFUL',
  STAR_MESSAGE_REQUEST: 'STAR_MESSAGE_REQUEST',
  STAR_MESSAGE_FAILED: 'STAR_MESSAGE_FAILED',
};

