const messageAction = {
  GET_MESSAGES_SUCCESSFUL: 'GET_MESSAGES_SUCCESSFUL',
  GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
  GET_MESSAGES_FAILED: 'GET_MESSAGES_FAILED',

  SEND_MESSAGE_SUCCESSFUL: 'SEND_MESSAGE_SUCCESSFUL',
  SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
  SEND_MESSAGE_FAILED: 'SEND_MESSAGE_FAILED',

  SAVE_MESSAGE_SUCCESSFUL: 'SAVE_MESSAGE_SUCCESSFUL',
  SAVE_MESSAGE_REQUEST: 'SAVE_MESSAGE_REQUEST',
  SAVE_MESSAGE_FAILED: 'SAVE_MESSAGE_FAILED',

  GET_MESSAGE_SUCCESSFUL: 'GET_MESSAGE_SUCCESSFUL',
  GET_MESSAGE_REQUEST: 'GET_MESSAGE_REQUEST',
  GET_MESSAGE_FAILED: 'GET_MESSAGE_FAILED',

  DELETE_MESSAGE_SUCCESSFUL: 'DELETE_MESSAGE_SUCCESSFUL',
  DELETE_MESSAGE_REQUEST: 'DELETE_MESSAGE_REQUEST',
  DELETE_MESSAGE_FAILED: 'DELETE_MESSAGE_FAILED',

  STAR_MESSAGE_SUCCESSFUL: 'STAR_MESSAGE_SUCCESSFUL',
  STAR_MESSAGE_REQUEST: 'STAR_MESSAGE_REQUEST',
  STAR_MESSAGE_FAILED: 'STAR_MESSAGE_FAILED',
};

export default messageAction;
