const modal_actions = {
  SHOW_SIGNIN: 'SHOW_SIGNIN',
  SHOW_SIGNUP: 'SHOW_SIGNUP',
  SHOW_NOTHING: 'SHOW_NOTHING',
  SHOW_PLEASE_LOGIN: 'SHOW_PLEASE_LOGIN',
  SHOW_EDIT: 'SHOW_EDIT',
  SHOW_CONFIRM_DELETE: 'SHOW_CONFIRM_DELETE',
  SHOW_COMPOSE_MESSAGE: 'SHOW_COMPOSE_MESSAGE',
};

export default modal_actions;
