const noticeAction = {
  UPLOAD_IMAGE_REQUEST: 'UPLOAD_IMAGE_REQUEST',
  UPLOAD_IMAGE_SUCCESSFUL: 'UPLOAD_IMAGE_SUCCESSFUL',
  UPLOAD_IMAGE_FAILED: 'UPLOAD_IMAGE_FAILED',

  UPLOAD_TEXT_REQUEST: 'UPLOAD_TEXT_REQUEST',
  UPLOAD_TEXT_SUCCESSFUL: 'UPLOAD_TEXT_SUCCESSFUL',
  UPLOAD_TEXT_FAILED: 'UPLOAD_TEXT_FAILED',
};

export default noticeAction;
