export default {
  GET_REPORTS_SUCCESSFUL: 'GET_REPORTS_SUCCESSFUL',
  GET_REPORTS_REQUEST: 'GET_REPORTS_REQUEST',
  GET_REPORTS_FAILED: 'GET_REPORTS_FAILED',

  GET_REPORT_SUCCESSFUL: 'GET_REPORT_SUCCESSFUL',
  GET_REPORT_REQUEST: 'GET_REPORT_REQUEST',
  GET_REPORT_FAILED: 'GET_REPORT_FAILED',

  DELETE_REPORT_SUCCESSFUL: 'DELETE_REPORT_SUCCESSFUL',
  DELETE_REPORT_REQUEST: 'DELETE_REPORT_REQUEST',
  DELETE_REPORT_FAILED: 'DELETE_REPORT_FAILED',

  UPDATE_REPORT_SUCCESSFUL: 'UPDATE_FISH_SUCCESSFUL',
  UPDATE_REPORT_REQUEST: 'UPDATE_FISH_REQUEST',
  UPDATE_REPORT_FAILED: 'UPDATE_FISH_FAILED',

  ADD_REPORT_SUCCESSFUL: 'ADD_REPORT_SUCCESSFUL',
  ADD_REPORT_REQUEST: 'ADD_REPORT_REQUEST',
  ADD_REPORT_FAILED: 'ADD_REPORT_FAILED',
};

